#include "TargetMap.hh"

std::unordered_map<std::string, std::string> target_map = {
    {"asm", "asm"}, {"assembly", "asm"}, {"s", "asm"},
    {"asm-intel", "asm-intel"}, {"intel", "asm-intel"}, {"intel-asm", "asm-intel"},
    {"asm-att", "asm-att"}, {"att", "asm-att"}, {"att-asm", "asm-att"},
    {"asm-arm", "asm-arm"}, {"arm-asm", "asm-arm"}, {"arm-assembly", "asm-arm"},
    {"asm-arm64", "asm-arm64"}, {"arm64-asm", "asm-arm64"}, {"aarch64-asm", "asm-arm64"},
    {"asm-riscv64", "asm-riscv64"}, {"riscv64-asm", "asm-riscv64"}, {"riscv-asm", "asm-riscv64"},
    {"asm-wasm", "asm-wasm"}, {"wasm-asm", "asm-wasm"}, {"wasm-assembly", "asm-wasm"},
    {"asm-ptx", "asm-ptx"}, {"ptx", "asm-ptx"}, {"ptx-asm", "asm-ptx"}, {"cuda-asm", "asm-ptx"},
    {"llvm", "llvm"}, {"ir", "llvm"},
    {"bitcode", "bitcode"}, {"bc", "bitcode"},
    {"obj", "obj"}, {"object", "obj"}, {"o", "obj"},
    {"win", "x86_64-pc-windows-msvc"}, {"exe", "x86_64-pc-windows-msvc"}, {"windows", "x86_64-pc-windows-msvc"}, {"win64", "x86_64-pc-windows-msvc"}, {"win-msvc", "x86_64-pc-windows-msvc"},
    {"win32", "i686-pc-windows-msvc"}, {"windows32", "i686-pc-windows-msvc"}, {"win32-msvc", "i686-pc-windows-msvc"},
    {"win-arm64", "aarch64-pc-windows-msvc"}, {"windows-arm64", "aarch64-pc-windows-msvc"},
    {"win-gnu", "x86_64-pc-windows-gnu"}, {"mingw", "x86_64-pc-windows-gnu"},
    {"linux", "x86_64-unknown-linux-gnu"}, {"linux64", "x86_64-unknown-linux-gnu"},
    {"linux32", "i686-unknown-linux-gnu"},
    {"linux-arm64", "aarch64-unknown-linux-gnu"},
    {"linux-arm", "arm-unknown-linux-gnueabihf"},
    {"linux-riscv64", "riscv64-unknown-linux-gnu"},
    {"linux-musl", "x86_64-unknown-linux-musl"},
    {"linux-arm64-musl", "aarch64-unknown-linux-musl"},
    {"macos", "x86_64-apple-darwin"}, {"darwin", "x86_64-apple-darwin"},
    {"macos-arm64", "arm64-apple-darwin"}, {"darwin-arm64", "arm64-apple-darwin"},
    {"ios", "x86_64-apple-ios"}, {"ios-arm64", "arm64-apple-ios"},
    {"freebsd", "x86_64-unknown-freebsd"}, {"freebsd-arm64", "aarch64-unknown-freebsd"},
    {"openbsd", "x86_64-unknown-openbsd"},
    {"netbsd", "x86_64-unknown-netbsd"},
    {"solaris", "x86_64-sun-solaris"},
    {"elf64", "x86_64-pc-linux-gnu"}, {"elf32", "i686-pc-linux-gnu"},
    {"elf-arm64", "aarch64-linux-gnu"}, {"elf-arm", "arm-linux-gnueabihf"},
    {"mips64", "mips64-unknown-linux-gnu"}, {"mips", "mips-unknown-linux-gnu"},
    {"ppc64", "powerpc64-unknown-linux-gnu"}, {"ppc64le", "powerpc64le-unknown-linux-gnu"},
    {"s390x", "s390x-unknown-linux-gnu"}, {"sparc64", "sparc64-unknown-linux-gnu"},
    {"haiku", "x86_64-unknown-haiku"},
    {"fuchsia", "x86_64-fuchsia"}, {"fuchsia-arm64", "aarch64-fuchsia"},
    {"wasm", "wasm32-unknown-unknown"}, {"webassembly", "wasm32-unknown-unknown"}, {"web", "wasm32-unknown-unknown"},
    {"wasm64", "wasm64-unknown-unknown"}, {"webassembly64", "wasm64-unknown-unknown"},
    {"cuda", "nvptx64-nvidia-cuda"}, {"ptx64", "nvptx64-nvidia-cuda"}, {"nvidia", "nvptx64-nvidia-cuda"},
    {"cuda32", "nvptx-nvidia-cuda"}, {"ptx32", "nvptx-nvidia-cuda"},
    {"arm64-raw", "aarch64"}, {"aarch64", "aarch64"}, {"arm64-bare", "aarch64"},
    {"arm-raw", "arm"}, {"arm", "arm"}, {"arm-bare", "arm"},
    {"riscv64-raw", "riscv64"}, {"riscv64", "riscv64"}, {"riscv64-bare", "riscv64"},
    {"riscv32-raw", "riscv32"}, {"riscv32", "riscv32"}, {"riscv32-bare", "riscv32"},
    {"thumb-raw", "thumb"}, {"thumb", "thumb"}, {"thumb-bare", "thumb"},
    {"bpf", "bpf"}, {"ebpf", "bpf"}, {"kernel", "bpf"},
    {"bpf-le", "bpfel"}, {"ebpf-le", "bpfel"}, {"bpfel", "bpfel"},
    {"bpf-be", "bpfeb"}, {"ebpf-be", "bpfeb"}, {"bpfeb", "bpfeb"},
    {"i", "interpret"}, {"interpret", "interpret"}
};